#+title: sc-dance Library: Readme
#+OPTIONS: toc:nil

* Purpose
This is a supercollider library networked live coding for dance and animation.
The  library plays animations on GODOT. It is recommended to run GODOT on the same computer as SuperCollider and sc-dance.

* Installation, Getting Started
To install, clone this repository and place it or link it inside the Extensions directory of your SuperCollider User support directory.

To try out:

1. Recompile the ScClass Library (control-shift-L in SuperCollider IDE).
2. Open Godot 4 on our computer.
3. In the Godot 4 application, import project =boy_and_birds= found in folder =./Godot_project=.
4. Start (play) project =boy_and_birds= in Godot.
5. Boot the local server in SuperCollider
6. Run the following line in SuperCollider to load and start playing the default animation:

#+begin_src
Avatar.load.sendToGodot.play
#+end_src

* Documentation
Documentation is found found in =./Documentation/sc-dance_documentation.pdf=.
* Example files
Code examples are found in =./Guides/=. (Under development).
